# Generated by Django 2.1.7 on 2019-02-26 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nop', models.IntegerField()),
                ('Travel_allow', models.IntegerField()),
                ('No_of_visit', models.IntegerField()),
                ('Rs_per_visit', models.IntegerField()),
                ('Research_fellow_id', models.IntegerField(choices=[(1, 'In-house'), (2, 'New'), (3, 'DNB')])),
                ('Remarks', models.TextField(blank=True)),
                ('Miscellan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Capital_equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Price', models.IntegerField()),
                ('Budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='clinical_studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sample_sanctioned', models.IntegerField()),
                ('no_patients_screened', models.IntegerField()),
                ('no_failures', models.IntegerField()),
                ('failures_reasons', models.CharField(max_length=100)),
                ('no_patients_enrolled', models.IntegerField()),
                ('no_patients_discontinued', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Co_Investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Co_name', models.CharField(max_length=100)),
                ('Co_designation', models.CharField(max_length=100)),
                ('Co_contact_no', models.CharField(max_length=20)),
                ('Co_email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='collaborations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institue', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Collab_type', models.TextField()),
                ('Ec_approval', models.BooleanField(max_length=2)),
                ('Authorship', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='comp_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_study_completion', models.DateField()),
                ('budeget_status', models.BooleanField(default=True)),
                ('original_protocol_changed', models.BooleanField(default=True)),
                ('ci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Co_Investigator')),
                ('clin_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clinical_studies')),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consum_name', models.CharField(max_length=250)),
                ('qty', models.IntegerField()),
                ('Rs_per_unit', models.IntegerField()),
                ('Catlog_no', models.IntegerField()),
                ('Name_of_manufact', models.CharField(max_length=250)),
                ('Total3', models.IntegerField(default=9)),
                ('consum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Director_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='expected_comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coll_date', models.DateTimeField()),
                ('data_analysis_date', models.DateTimeField()),
                ('write_up', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_improved_clin_practice', models.TextField()),
                ('any_other', models.TextField()),
                ('problems_faced', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Investigation1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.CharField(max_length=250)),
                ('exist_test_id', models.IntegerField(choices=[(1, 'yes'), (2, 'no')])),
                ('No_of_pat', models.IntegerField()),
                ('Tarrif', models.IntegerField()),
                ('Total1', models.IntegerField(default=10)),
                ('invest1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.CharField(max_length=250)),
                ('exist_test_id', models.IntegerField(choices=[(1, 'yes'), (2, 'no')])),
                ('No_of_pat', models.IntegerField()),
                ('Followup', models.IntegerField()),
                ('Tarrif', models.IntegerField()),
                ('Total2', models.IntegerField(default=19)),
                ('invest2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='lab_study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nos_sanctioned', models.IntegerField()),
                ('nos_collected', models.IntegerField()),
                ('nos_tested', models.IntegerField()),
                ('nos_rejected', models.TextField()),
                ('new_tech_established', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Out_funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.TextField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=100)),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='paper_presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_level', models.CharField(choices=[(1, 'Local'), (2, 'National'), (3, 'International')], max_length=100)),
                ('conf_name', models.TextField()),
                ('Year', models.DateTimeField()),
                ('other', models.TextField()),
                ('pblished', models.CharField(choices=[(1, 'YES'), (2, 'NO')], max_length=100)),
                ('certificate', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='pat_sel_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('define_pop', models.TextField()),
                ('In_criteria', models.TextField()),
                ('Ex_criteria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Principal_investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('P_Dept', models.CharField(max_length=100)),
                ('p_contact', models.CharField(max_length=20)),
                ('p_email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('p_designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='prog_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_comencenment', models.DateTimeField()),
                ('project_rate', models.TextField()),
                ('brief_summary', models.CharField(choices=[(1, 'patient'), (2, 'laboratory')], max_length=100)),
                ('provisonal', models.TextField()),
                ('exp_date_completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.expected_comp')),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.feedback')),
                ('lab_study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lab_study')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paper_presentation')),
                ('patient_clinical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clinical_studies')),
            ],
        ),
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code_no', models.CharField(editable=False, max_length=100)),
                ('period_of_data', models.IntegerField()),
                ('enroll_period', models.IntegerField()),
                ('budget_estimate', models.IntegerField()),
                ('project_title', models.CharField(max_length=256)),
                ('appr_date_erb', models.DateField()),
                ('sample_size', models.IntegerField()),
                ('choose_fund', models.CharField(choices=[('H', 'HH'), ('O', 'Out')], max_length=100)),
                ('Hypothesis', models.TextField()),
                ('Rationale', models.TextField()),
                ('Aim', models.TextField()),
                ('objectives', models.TextField()),
                ('Lit_review', models.TextField()),
                ('preliminary_work', models.TextField()),
                ('Research_plan', models.TextField()),
                ('Co_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Co_Investigator')),
                ('Funding_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Out_funding')),
                ('PI_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Principal_investigator')),
            ],
        ),
        migrations.CreateModel(
            name='protocol_amend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_been_amended', models.CharField(choices=[(1, 'YES'), (2, 'NO')], max_length=100)),
                ('comm_appr', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Salaryy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Study', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Total0', models.IntegerField(default=10)),
                ('Salary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='sec_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Std_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('st_contact_no', models.CharField(max_length=100)),
                ('st_email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('st_study_purpose', models.CharField(choices=[('D', 'DNB'), ('M', 'MSc'), ('P', 'PhD'), ('O', 'Others')], max_length=100)),
                ('st_designation', models.CharField(default=False, max_length=100)),
                ('any_pub', models.TextField(default=False)),
                ('st_collab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.collaborations')),
            ],
        ),
        migrations.CreateModel(
            name='study_design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_report', models.CharField(choices=[('O', 'Cohort,Prospective'), ('ER', 'Open-(non blinded)'), ('EN', 'Non-Randomized')], max_length=100)),
                ('cs_series', models.CharField(choices=[('O', 'Cohort,Retrospective'), ('ER', 'Single-blind'), ('EN', 'Study of diagnostic efficacy')], max_length=100)),
                ('srvey', models.CharField(choices=[('OC', 'Case control'), ('OS', 'Cross-sectional'), ('ERD', 'Double blind'), ('ERT', 'Triple blind')], max_length=100)),
                ('others', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='study_step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informed_consent', models.CharField(choices=[('W', 'Written'), ('T', 'Telephonic'), ('V', 'Waiver'), ('O', 'Other')], max_length=100)),
                ('Intevention_code', models.CharField(choices=[('D', 'Drug Studies For approved indication'), ('O', 'Off-label use of drugs approved for other indication'), ('S', 'Surgery'), ('T', 'Special Test'), ('Q', 'Questionaire'), ('A', 'Any other')], max_length=100)),
                ('Questionaire_valid', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('Regional_lang', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('med_id', models.URLField()),
                ('surgical_id', models.URLField()),
                ('lab_id', models.URLField()),
                ('outcome_measure_id', models.TextField()),
                ('methodology', models.TextField()),
                ('proforma', models.TextField()),
                ('translation', models.TextField()),
                ('budget_id', models.CharField(max_length=100)),
                ('outside_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Out_funding')),
                ('patient_sel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pat_sel_id')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_coll_period', models.IntegerField()),
                ('retro_period', models.IntegerField()),
                ('patient_part', models.IntegerField()),
                ('Thesis_submis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='work_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical', models.TextField()),
                ('Investigations', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='study_step',
            name='work_up_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.work_up'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='Time_frame_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Time_Frame'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='completion_report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.comp_report'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='feedback_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.feedback'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='progress_report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.prog_report'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='st_design_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.study_design'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='stud_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Std_details'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='study_steps_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.study_step'),
        ),
        migrations.AddField(
            model_name='prog_report',
            name='protocol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.protocol_amend'),
        ),
        migrations.AddField(
            model_name='comp_report',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Principal_investigator'),
        ),
        migrations.AddField(
            model_name='comp_report',
            name='paper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paper_presentation'),
        ),
        migrations.AddField(
            model_name='comp_report',
            name='protocol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.protocol_amend'),
        ),
        migrations.AddField(
            model_name='comp_report',
            name='st_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Std_details'),
        ),
    ]
